<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    integer         irn
    text short      DarGlobalUniqueIdentifier
    integer         CatAccessionYearLocal
    integer         DarCatalogNumberNumeric
    tuple           PriAccessionNumberRef
      text short      AccAccessionNo
    end
    text short      DarCatalogNumber
    table           OtherNums
      text short      CatOtherNumbersType
      text long       CatOtherNumbersValue
    end
    table           Description
      text long       DesKDescription
      text short      DesKType
    end
    table           DesUseClassification_tab
      text short      DesUseClassification
    end
    table           EcbPartsUsed_tab
      text short      EcbPartsUsed
    end
    table           DesEthnicGroupSubgroup_tab
      text short      DesEthnicGroupSubgroup
    end
    table           AttPeriod_tab
      text short      AttPeriod
    end
    table           DesMaterials_tab
      text short      DesMaterials
    end
    tuple           ColCollectionEventRef
      tuple           ColSiteRef
        integer         esites_irn
        text short      PolContinent
        text short      PolPD1
        text short      PolPD2
        text short      PolPD3
        text short      PolPopn
      end
    end
    text long       DarLocality
    integer         CatItemsCat
    integer         CatItemsInv
    table           DesObj
      text short      DesObjectName
      text short      DesObjectType
    end
    text short      DarCollector
    text short      CatRecordType
    text short      DesSubjectCode
    text short      DesPeriod
    text long       DesTechnicalDescription
    table           ColContinentLocal_tab
      text short      ColContinentLocal
    end
    table           ColCountryLocal_tab
      text short      ColCountryLocal
    end
    table           ColProvinceStateTerritoryLocal_tab
      text short      ColProvinceStateTerritoryLocal
    end
    table           ColDistrictCountyShireLocal_tab
      text short      ColDistrictCountyShireLocal
    end
    table           ColTownshipLocal_tab
      text short      ColTownshipLocal
    end
    integer         CatObjectCount
    integer         CatItemsSub
    text short      CatLegalStatus
    integer         CatAnthroCatalogNumber
    text long       CatSubNumbers
    table           Multimedia
      text short      AudIdentifier
      text short      AudAccessURI
      text short      AudCitation
      text short      emul_AdmPublishWebNoPassword
    end
    table           RefReferenceRef_tab
      integer         ebiblio_irn
      text long       ebiblio_SummaryData
    end
    table           RelObjectsRef_tab
      integer         ecatrel_irn
      text short      ecatrel_SummaryData
      text short      ecatrel_DarGlobalUniqueIdentifier
    end
  end
?>
<!-- Data -->
<table name="ecatalogue">

  <!-- Row 1 -->
  <tuple>
    <atom name="irn">1312411</atom>
    <atom name="DarGlobalUniqueIdentifier">03b53a6a-99ca-43ee-b8c5-ecc498336b10</atom>
    <atom name="CatAccessionYearLocal">1904</atom>
    <atom name="DarCatalogNumberNumeric">8143</atom>
    <tuple name="PriAccessionNumberRef">
      <atom name="AccAccessionNo">862</atom>
    </tuple>
    <atom name="DarCatalogNumber">8143.nosub[1]</atom>
    <table name="OtherNums">
      <tuple>
        <atom name="CatOtherNumbersType">Publication number</atom>
        <atom name="CatOtherNumbersValue">306</atom>
      </tuple>
      <tuple>
        <atom name="CatOtherNumbersType">Publication number</atom>
        <atom name="CatOtherNumbersValue">XVII</atom>
      </tuple>
      <tuple>
        <atom name="CatOtherNumbersType">Image number</atom>
        <atom name="CatOtherNumbersValue">99448</atom>
      </tuple>
      <tuple>
        <atom name="CatOtherNumbersType">Image number</atom>
        <atom name="CatOtherNumbersValue">99539</atom>
      </tuple>
      <tuple>
        <atom name="CatOtherNumbersType">Image number</atom>
        <atom name="CatOtherNumbersValue">99540</atom>
      </tuple>
      <tuple>
        <atom name="CatOtherNumbersType">Image number</atom>
        <atom name="CatOtherNumbersValue">CSA58327</atom>
      </tuple>
      <tuple>
        <atom name="CatOtherNumbersType">Image number</atom>
        <atom name="CatOtherNumbersValue">112461</atom>
      </tuple>
      <tuple>
        <atom name="CatOtherNumbersType">Image number</atom>
        <atom name="CatOtherNumbersValue">112834</atom>
      </tuple>
      <tuple>
        <atom name="CatOtherNumbersType">Image number</atom>
        <atom name="CatOtherNumbersValue">112835</atom>
      </tuple>
      <tuple>
        <atom name="CatOtherNumbersType">Image number</atom>
        <atom name="CatOtherNumbersValue">112836</atom>
      </tuple>
      <tuple>
        <atom name="CatOtherNumbersType">Image number</atom>
        <atom name="CatOtherNumbersValue">GN87049_30</atom>
      </tuple>
      <tuple>
        <atom name="CatOtherNumbersType">Image number</atom>
        <atom name="CatOtherNumbersValue">GN79715</atom>
      </tuple>
      <tuple>
        <atom name="CatOtherNumbersType">Image number</atom>
        <atom name="CatOtherNumbersValue">GN83906_4</atom>
      </tuple>
      <tuple>
        <atom name="CatOtherNumbersType">Image number</atom>
        <atom name="CatOtherNumbersValue">A99566</atom>
      </tuple>
    </table>
    <table name="Description">
      <tuple>
        <atom name="DesKDescription">tusk</atom>
        <atom name="DesKType">Basic Description</atom>
      </tuple>
      <tuple>
        <atom name="DesKDescription">carved elephant tusk; note on back of catalog card: men and spear, [2 illegible words], birds, snake eating man, men vs [illegible word]; Dimensions: L = 223.5 cm; 7'4"; 88"</atom>
        <atom name="DesKType">Full Description</atom>
      </tuple>
      <tuple>
        <atom name="DesKDescription">The Art of Benin Catalog entry:
306. TUSK. Ivory. L. 7'4". CNHM 8143. Plate XVII A very fine ivory tusk carved all over with figures and animal forms. The second and fifth figures up, on the front of the tusk (on the outer side of the circumference), are representations of Oba Ohe, who was mentioned under "Shield Plaques." Figures f Europeans and other dignitaries can be seen. Other forms include crocodile heads, a clenched hand, a turkey cock, crocodile, leopard, mud fish, cock, and elephant head with the trunk ending in a human hand. In the detail of the tusk illustrated is shown the figure of a European holding the foot of a leopard with his right hand. Above his hat is the head of a crocodile. To his left is the head of an elephant with its trunk ending in a human hand. Below the figure's feet is a leaf form similar to that found on altars to the hand.</atom>
        <atom name="DesKType">Full Description</atom>
      </tuple>
    </table>
    <table name="DesUseClassification_tab">
      <tuple>
        <atom name="DesUseClassification">Ceremonial Artifact</atom>
      </tuple>
    </table>
    <table name="EcbPartsUsed_tab">
      <tuple>
        <atom name="EcbPartsUsed">tusk</atom>
      </tuple>
    </table>
    <table name="DesEthnicGroupSubgroup_tab">
      <tuple>
        <atom name="DesEthnicGroupSubgroup">Edo</atom>
      </tuple>
    </table>
    <table name="DesMaterials_tab">
      <tuple>
        <atom name="DesMaterials">animal tooth; elephant tusk - ivory</atom>
      </tuple>
    </table>
    <tuple name="ColCollectionEventRef">
      <tuple name="ColSiteRef">
        <atom name="esites_irn">400853</atom>
        <atom name="PolContinent">Africa</atom>
        <atom name="PolPD1">Nigeria</atom>
        <atom name="PolPD2">Edo</atom>
        <atom name="PolPD3">Benin Kingdom</atom>
        <atom name="PolPopn">Benin City</atom>
      </tuple>
    </tuple>
    <atom name="DarLocality">Benin City</atom>
    <atom name="CatItemsCat">1</atom>
    <atom name="CatItemsInv">1</atom>
    <atom name="DarCollector">Collector</atom>
    <atom name="CatRecordType">Single</atom>
    <atom name="DesSubjectCode">2202: West Africa: carvings, castings: ivory</atom>
    <atom name="DesPeriod"></atom>
    <atom name="DesTechnicalDescription"></atom>
    <table name="ColContinentLocal_tab">
      <tuple>
        <atom name="ColContinentLocal">Africa</atom>
      </tuple>
    </table>
    <table name="ColCountryLocal_tab">
      <tuple>
        <atom name="ColCountryLocal">Nigeria</atom>
      </tuple>
    </table>
    <table name="ColProvinceStateTerritoryLocal_tab">
      <tuple>
        <atom name="ColProvinceStateTerritoryLocal">Benin Kingdom</atom>
      </tuple>
    </table>
    <table name="ColTownshipLocal_tab">
      <tuple>
        <atom name="ColTownshipLocal">Benin City</atom>
      </tuple>
    </table>
    <atom name="CatObjectCount">1</atom>
    <atom name="CatItemsSub">0</atom>
    <atom name="CatLegalStatus">Permanent Collection</atom>
    <atom name="CatAnthroCatalogNumber">8143</atom>
    <atom name="CatSubNumbers">nosub[1]</atom>
    <table name="Multimedia">
      <tuple>
        <atom name="AudIdentifier">dcb87a50-a8b2-4237-b7e3-3508dcd89169</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/73/514/A112461c.jpg</atom>
        <atom name="AudCitation">Courtesy of: J. Weinstein. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/dcb87a50-a8b2-4237-b7e3-3508dcd89169 (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">d70aa770-db59-4728-a176-592c89019ff5</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/2243/413/CSA58327_8143_Edit.jpg</atom>
        <atom name="AudCitation">Courtesy of: C. J. Philipp. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/d70aa770-db59-4728-a176-592c89019ff5 (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">a8ccda11-84db-4fc2-ac93-30b67d336c33</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/84/719/A99540.jpg</atom>
        <atom name="AudCitation">(c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/a8ccda11-84db-4fc2-ac93-30b67d336c33 (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">3cc23b3f-7ccc-40b0-bef4-8ab14ce6bf6f</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/1356/812/A112835_6c.jpg</atom>
        <atom name="AudCitation">Courtesy of: J. Weinstein. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/3cc23b3f-7ccc-40b0-bef4-8ab14ce6bf6f (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">8f7d0dc9-c4df-4021-95b6-bb8935865513</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/1356/810/A112835_3c.jpg</atom>
        <atom name="AudCitation">Courtesy of: J. Weinstein. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/8f7d0dc9-c4df-4021-95b6-bb8935865513 (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">8d962990-9683-4e06-9f16-aea9789b9ca4</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/1356/814/A112835_10c.jpg</atom>
        <atom name="AudCitation">Courtesy of: J. Weinstein. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/8d962990-9683-4e06-9f16-aea9789b9ca4 (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">85959424-47c2-4504-9df6-6ffcab5d778e</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/1356/817/A112836_10c.jpg</atom>
        <atom name="AudCitation">Courtesy of: J. Weinstein. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/85959424-47c2-4504-9df6-6ffcab5d778e (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">754a85df-31f5-4061-bea2-91369c629e83</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/100/961/A99539.jpg</atom>
        <atom name="AudCitation">(c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/754a85df-31f5-4061-bea2-91369c629e83 (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">3689ceaf-c784-4cfb-ad11-8c77a3ed1644</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/73/922/A112834_2c.jpg</atom>
        <atom name="AudCitation">Courtesy of: J. Weinstein. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/3689ceaf-c784-4cfb-ad11-8c77a3ed1644 (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">1bcf1e79-011c-4ca1-a9bb-e752ccfb1492</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/73/921/A112834_1c.jpg</atom>
        <atom name="AudCitation">Courtesy of: J. Weinstein. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/1bcf1e79-011c-4ca1-a9bb-e752ccfb1492 (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">c8181248-f06b-4c0f-a0d2-06a7f2d9ab90</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/102/124/CSA58327.jpg</atom>
        <atom name="AudCitation">(c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/c8181248-f06b-4c0f-a0d2-06a7f2d9ab90 (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">3297a964-bd6c-42ea-a232-9f0b2c316fae</atom>
        <atom name="AudAccessURI"></atom>
        <atom name="AudCitation">(c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/3297a964-bd6c-42ea-a232-9f0b2c316fae (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">No</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">fd805cb9-ff9b-4a87-b2a8-eabb3eafd113</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/1356/815/A112836_4c.jpg</atom>
        <atom name="AudCitation">Courtesy of: J. Weinstein. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/fd805cb9-ff9b-4a87-b2a8-eabb3eafd113 (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">7efcf662-cfa0-4a6c-82f1-f35021759d39</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/2040/207/GN87049_30.jpg</atom>
        <atom name="AudCitation">Courtesy of: J. Balodimas. (c) Field Museum of Natural History. https://mm.fieldmuseum.org/7efcf662-cfa0-4a6c-82f1-f35021759d39 (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">cf432cf2-947b-4368-9b92-0ca22615812a</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/2032/932/GN79715.jpg</atom>
        <atom name="AudCitation">Courtesy of: J. Bayalis. (c) Field Museum of Natural History. https://mm.fieldmuseum.org/cf432cf2-947b-4368-9b92-0ca22615812a (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">15676409-38ec-45bf-8e12-3afb4bf4abf8</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/2102/425/A99566.jpg</atom>
        <atom name="AudCitation">(c) Field Museum of Natural History. https://mm.fieldmuseum.org/15676409-38ec-45bf-8e12-3afb4bf4abf8 (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">c3d29c28-bd93-4e6c-935e-9298d84cab27</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/2036/093/GN83906_4.jpg</atom>
        <atom name="AudCitation">Courtesy of: R. Testa. (c) Field Museum of Natural History. https://mm.fieldmuseum.org/c3d29c28-bd93-4e6c-935e-9298d84cab27 (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">a0c4cd9f-838d-4552-bc77-950cb9caf47b</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/343/326/8143CC.pdf</atom>
        <atom name="AudCitation">Courtesy of: C. J. Philipp, J. W. Kennedy. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/a0c4cd9f-838d-4552-bc77-950cb9caf47b (accessed on 12 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2 -->
  <tuple>
    <atom name="irn">123456</atom>
    <atom name="DarGlobalUniqueIdentifier">0123abcde-12345-abcdef</atom>
    <atom name="CatAccessionYearLocal">1910</atom>
    <atom name="DarCatalogNumberNumeric">8765-sample</atom>
    <tuple name="PriAccessionNumberRef">
      <atom name="AccAccessionNo">789-sample</atom>
    </tuple>
    <atom name="DarCatalogNumber">8765.nosub[1]</atom>
    <table name="OtherNums">
      <tuple>
        <atom name="CatOtherNumbersType">Publication number</atom>
        <atom name="CatOtherNumbersValue">3456-sample</atom>
      </tuple>
    </table>
    <table name="Description">
      <tuple>
        <atom name="DesKDescription">sample-data description</atom>
        <atom name="DesKType">Basic Description</atom>
      </tuple>
    </table>
    <table name="DesUseClassification_tab">
      <tuple>
        <atom name="DesUseClassification">sample-data use classification</atom>
      </tuple>
    </table>
    <table name="EcbPartsUsed_tab">
      <tuple>
        <atom name="EcbPartsUsed">sample-data parts used</atom>
      </tuple>
    </table>
    <table name="DesEthnicGroupSubgroup_tab">
      <tuple>
        <atom name="DesEthnicGroupSubgroup">Sample-data Group</atom>
      </tuple>
    </table>
    <table name="DesMaterials_tab">
      <tuple>
        <atom name="DesMaterials">sample-data materials</atom>
      </tuple>
    </table>
    <tuple name="ColCollectionEventRef">
      <tuple name="ColSiteRef">
        <atom name="esites_irn">45678</atom>
        <atom name="PolContinent">Africa</atom>
        <atom name="PolPD1">Nigeria</atom>
        <atom name="PolPD2">Edo</atom>
        <atom name="PolPD3">Benin Kingdom</atom>
        <atom name="PolPopn">Sample-data city</atom>
      </tuple>
    </tuple>
    <atom name="DarLocality">Benin City</atom>
    <atom name="CatItemsCat">1</atom>
    <atom name="CatItemsInv">1</atom>
    <atom name="DarCollector">Collector</atom>
    <atom name="CatRecordType">Single</atom>
    <atom name="DesSubjectCode">sample-code: sample-subjects</atom>
    <atom name="DesPeriod"></atom>
    <atom name="DesTechnicalDescription"></atom>
    <table name="ColContinentLocal_tab">
      <tuple>
        <atom name="ColContinentLocal">Africa</atom>
      </tuple>
    </table>
    <table name="ColCountryLocal_tab">
      <tuple>
        <atom name="ColCountryLocal">Nigeria</atom>
      </tuple>
    </table>
    <table name="ColProvinceStateTerritoryLocal_tab">
      <tuple>
        <atom name="ColProvinceStateTerritoryLocal">Benin Kingdom</atom>
      </tuple>
    </table>
    <table name="ColTownshipLocal_tab">
      <tuple>
        <atom name="ColTownshipLocal">Benin City</atom>
      </tuple>
    </table>
    <atom name="CatObjectCount">1</atom>
    <atom name="CatItemsSub">0</atom>
    <atom name="CatLegalStatus">Permanent Collection</atom>
    <atom name="CatAnthroCatalogNumber">8765-sample</atom>
    <atom name="CatSubNumbers">nosub[1]</atom>
    <table name="Multimedia">
      <tuple>
        <atom name="AudIdentifier">abcdef-12345-987654-gfedcba</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/1234/567/sample-data.jpg</atom>
        <atom name="AudCitation">Courtesy of: sample-data https://mm.fieldmuseum.org/abcdef-12345-987654-gfedcba (accessed on 16 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3 -->
  <tuple>
    <atom name="irn">234567</atom>
    <atom name="DarGlobalUniqueIdentifier">1234abcde-23456-abcdef</atom>
    <atom name="CatAccessionYearLocal">1911</atom>
    <atom name="DarCatalogNumberNumeric">9876-sample</atom>
    <tuple name="PriAccessionNumberRef">
      <atom name="AccAccessionNo">678-sample</atom>
    </tuple>
    <atom name="DarCatalogNumber">9876.nosub[1]</atom>
    <table name="OtherNums">
      <tuple>
        <atom name="CatOtherNumbersType">Publication number</atom>
        <atom name="CatOtherNumbersValue">23456-sample</atom>
      </tuple>
    </table>
    <table name="Description">
      <tuple>
        <atom name="DesKDescription">sample-data description</atom>
        <atom name="DesKType">Basic Description</atom>
      </tuple>
    </table>
    <table name="DesEthnicGroupSubgroup_tab">
      <tuple>
        <atom name="DesEthnicGroupSubgroup">Sample-data Group</atom>
      </tuple>
    </table>
    <table name="DesMaterials_tab">
      <tuple>
        <atom name="DesMaterials">sample-data materials</atom>
      </tuple>
    </table>
    <tuple name="ColCollectionEventRef">
      <tuple name="ColSiteRef">
        <atom name="esites_irn">45678</atom>
        <atom name="PolContinent">Africa</atom>
        <atom name="PolPD1">Nigeria</atom>
        <atom name="PolPD2">Edo</atom>
        <atom name="PolPD3">Benin Kingdom</atom>
        <atom name="PolPopn">Sample-data city</atom>
      </tuple>
    </tuple>
    <atom name="DarLocality">Benin City</atom>
    <atom name="CatItemsCat">1</atom>
    <atom name="CatItemsInv">1</atom>
    <atom name="DarCollector">Collector</atom>
    <atom name="CatRecordType">Single</atom>
    <atom name="DesSubjectCode">sample-code: sample-subjects</atom>
    <atom name="DesPeriod"></atom>
    <atom name="DesTechnicalDescription"></atom>
    <table name="ColContinentLocal_tab">
      <tuple>
        <atom name="ColContinentLocal">Africa</atom>
      </tuple>
    </table>
    <table name="ColCountryLocal_tab">
      <tuple>
        <atom name="ColCountryLocal">Nigeria</atom>
      </tuple>
    </table>
    <table name="ColProvinceStateTerritoryLocal_tab">
      <tuple>
        <atom name="ColProvinceStateTerritoryLocal">Benin Kingdom</atom>
      </tuple>
    </table>
    <table name="ColTownshipLocal_tab">
      <tuple>
        <atom name="ColTownshipLocal">Benin City</atom>
      </tuple>
    </table>
    <atom name="CatObjectCount">1</atom>
    <atom name="CatItemsSub">0</atom>
    <atom name="CatLegalStatus">Permanent Collection</atom>
    <atom name="CatAnthroCatalogNumber">9876-sample</atom>
    <atom name="CatSubNumbers">nosub[1]</atom>
    <table name="Multimedia">
      <tuple>
        <atom name="AudIdentifier">bcdefg-23456-9876543-fedcba</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/1234/567/sample-data.jpg</atom>
        <atom name="AudCitation">Courtesy of: sample-data https://mm.fieldmuseum.org/abcdef-12345-987654-gfedcba (accessed on 16 Aug 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
    </table>
  </tuple>
</table>
