<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    integer         irn
    text short      DarGlobalUniqueIdentifier
    table           MulMultiMediaRef_tab
      date            AdmDateInserted
      date            AdmDateModified
      text short      AdmPublishWebNoPassword
      text short      AudAccessURI
      text long       AudACDescription
      text short      AudAssociatedObservation
      text short      AudAssociatedSpecimen
      text short      AudCaptureDevice
      text short      AudCitation
      text short      AudDerivedFrom
      text short      AudFundingAttribution
      text short      AudIdentifier
      text short      AudLifeStage
      text long       AudNumbers
      text long       AudRelatedGeography
      text long       AudRelatedResourceID
      text short      AudSex
      text short      AudSubjectOrientation
      table           AudSubjectPart_tab
        text short      AudSubjectPart
      end
      text long       AudTaxonCoverage
      text long       AudTemporalCoverage
      text long       AudVernacularName
      text short      ChaAudioLength
      integer         ChaFileSize
      text short      ChaImageHeight
      text short      ChaImageWidth
      text short      ChaMd5Sum
      text long       ChaMediaForm
      text short      ChaVideoFilmLength
      text long       DetResourceType
      text short      DetResourceSubtype
      table           dates
        date            DetResourceDetailsDate
        text long       DetResourceDetailsDescription
      end
      tuple           DetMediaRightsRef
        text long       SummaryData
      end
      table           DetSubject_tab
        text short      DetSubject
      end
      text short      MulMimeType
      text short      MulMimeFormat
      text long       MulIdentifier
      table           creator
        table           NamExternalReferences_tab
          text short      NamExternalReferences
        end
        text long       NamFullName
        integer         irn
        text short      MulMultimediaCreatorRole
      end
      text long       RightsAcknowledgeLocal
      text long       MulTitle
      integer         irn
      table           supplementary
        integer         SupFileSize
        text short      SupMD5Checksum
        text short      SupMimeFormat
        text short      SupMimeType
      end
    end
  end
?>
<!-- Data -->
<table name="ecatalogue">

  <!-- Row 1 -->
  <tuple>
    <atom name="irn">3808027</atom>
    <atom name="DarGlobalUniqueIdentifier">a3e1ffc0-3c29-4627-8be6-cb83f4257352</atom>
  </tuple>

  <!-- Row 2 -->
  <tuple>
    <atom name="irn">3808034</atom>
    <atom name="DarGlobalUniqueIdentifier">d36d9d0c-f684-4308-8e18-34f5ac5cb01d</atom>
  </tuple>

  <!-- Row 3 -->
  <tuple>
    <atom name="irn">3808032</atom>
    <atom name="DarGlobalUniqueIdentifier">f80828f0-6c10-4486-851d-ed8d9a1c260f</atom>
  </tuple>

  <!-- Row 4 -->
  <tuple>
    <atom name="irn">3630556</atom>
    <atom name="DarGlobalUniqueIdentifier">29cf43da-7863-4f6a-af06-b88df84cfd24</atom>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <atom name="AdmDateInserted">2013-04-11</atom>
        <atom name="AdmDateModified">2021-03-11</atom>
        <atom name="AdmPublishWebNoPassword">No</atom>
        <atom name="AudAccessURI"></atom>
        <atom name="AudACDescription">scan of catalog card</atom>
        <atom name="AudAssociatedObservation"></atom>
        <atom name="AudAssociatedSpecimen">d28df62e-9e2d-4f33-a4e0-75776194c10e | 86893b0e-f03e-42eb-ae92-ea85b50bc2a8 | a81cbf80-3c41-4e55-8a2c-93aa6b4015a7 | 747c7e7a-e51b-40af-8f7e-d097da5a090d | 3aec34f1-aad9-4db8-a042-6912d99f8fab | aa3bff4f-51a6-4901-ba55-fc309aa24e9d | eb052625-228a-4868-bc</atom>
        <atom name="AudCaptureDevice"></atom>
        <atom name="AudCitation">Courtesy of: C. Pontone. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/aed844e7-f998-4d0d-87d7-d35a4cde098f (accessed on 11 Mar 2021)</atom>
        <atom name="AudDerivedFrom"></atom>
        <atom name="AudFundingAttribution"></atom>
        <atom name="AudIdentifier">aed844e7-f998-4d0d-87d7-d35a4cde098f</atom>
        <atom name="AudLifeStage"></atom>
        <atom name="AudNumbers">23495.269 | 23495.270 | 23495.20 | 23495.21 | 23495.22 | 23495.23 | 23495.202 | 23495.203 | 23495.204 | 23495.142 | 23495.143 | 23495.144 | 23495.91 | 23495.92 | 23495.93 | 23495.94 | 23495.95 | 23495.96 | 23495.97 | 23495.98 | 23495.99 | 23495.100 | 23495.101 | 23495.102 | 23495.130 | 23495.131 | 23495.132 | 23495.10 | 23495.11 | 23495.12 | 23495.13 | 23495.277 | 23495.278 | 23495.157 | 23495.158 | 23495.159 | 23495.145 | 23495.146 | 23495.147 | 23495.127 | 23495.128 | 23495.129 | 23495.112 | 23495.113 | 23495.114 | 23495.184 | 23495.185 | 23495.186 | 23495.148 | 23495.149 | 23495.150 | 23495.271 | 23495.272 | 23495.118 | 23495.119 | 23495.120 | 23495.106 | 23495.107 | 23495.108 | 23495.257 | 23495.258 | 23495.151 | 23495.152 | 23495.153 | 23495.31 | 23495.32 | 23495.33 | 23495.34 | 23495.136 | 23495.137 | 23495.138 | 23495.265 | 23495.266 | 23495.109 | 23495.110 | 23495.111 | 23495.261 | 23495.262 | 23495.115 | 23495.116 | 23495.117 | 23495.211 | 23495.212 | 23495.215 | 23495.216 | 2</atom>
        <atom name="AudRelatedGeography">México, Yucatán, North America</atom>
        <atom name="AudRelatedResourceID"></atom>
        <atom name="AudSex"></atom>
        <atom name="AudSubjectOrientation"></atom>
        <atom name="AudTaxonCoverage">xx99: Mexico: Yucatan: archaeology</atom>
        <atom name="AudTemporalCoverage"></atom>
        <atom name="AudVernacularName"></atom>
        <atom name="ChaAudioLength"></atom>
        <atom name="ChaFileSize">248588</atom>
        <atom name="ChaImageHeight"></atom>
        <atom name="ChaImageWidth"></atom>
        <atom name="ChaMd5Sum">441bdd6cd6c03b9035ee6f2073edfe43</atom>
        <atom name="ChaMediaForm">PDF document</atom>
        <atom name="ChaVideoFilmLength"></atom>
        <atom name="DetResourceType">Text</atom>
        <atom name="DetResourceSubtype"></atom>
        <tuple name="DetMediaRightsRef">
          <atom name="SummaryData">(c) Field Museum of Natural History - CC BY-NC 4.0</atom>
        </tuple>
        <atom name="MulMimeType">application</atom>
        <atom name="MulMimeFormat">pdf</atom>
        <atom name="MulIdentifier">23495CC.pdf</atom>
        <table name="creator">
          <tuple>
            <atom name="NamFullName">Cassie Pontone</atom>
            <atom name="irn">170222</atom>
            <atom name="MulMultimediaCreatorRole">Creator</atom>
          </tuple>
        </table>
        <atom name="RightsAcknowledgeLocal">Please cite this as: (c) The Field Museum (DATE) CC-BY-NC</atom>
        <atom name="MulTitle">23495 Catalog Card</atom>
        <atom name="irn">428744</atom>
      </tuple>
      <tuple>
        <atom name="AdmDateInserted">2017-02-03</atom>
        <atom name="AdmDateModified">2021-03-11</atom>
        <atom name="AdmPublishWebNoPassword">No</atom>
        <atom name="AudAccessURI"></atom>
        <atom name="AudACDescription">scan of tag found with object</atom>
        <atom name="AudAssociatedObservation"></atom>
        <atom name="AudAssociatedSpecimen">d28df62e-9e2d-4f33-a4e0-75776194c10e | 86893b0e-f03e-42eb-ae92-ea85b50bc2a8 | a81cbf80-3c41-4e55-8a2c-93aa6b4015a7 | 747c7e7a-e51b-40af-8f7e-d097da5a090d | 3aec34f1-aad9-4db8-a042-6912d99f8fab | aa3bff4f-51a6-4901-ba55-fc309aa24e9d | eb052625-228a-4868-bc</atom>
        <atom name="AudCaptureDevice"></atom>
        <atom name="AudCitation">Courtesy of: C. J. Philipp. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/fc7f8eb5-0253-497d-9e5e-f299bc54d0bf (accessed on 11 Mar 2021)</atom>
        <atom name="AudDerivedFrom"></atom>
        <atom name="AudFundingAttribution"></atom>
        <atom name="AudIdentifier">fc7f8eb5-0253-497d-9e5e-f299bc54d0bf</atom>
        <atom name="AudLifeStage"></atom>
        <atom name="AudNumbers">23495.269 | 23495.270 | 23495.20 | 23495.21 | 23495.22 | 23495.23 | 23495.202 | 23495.203 | 23495.204 | 23495.142 | 23495.143 | 23495.144 | 23495.91 | 23495.92 | 23495.93 | 23495.94 | 23495.95 | 23495.96 | 23495.97 | 23495.98 | 23495.99 | 23495.100 | 23495.101 | 23495.102 | 23495.130 | 23495.131 | 23495.132 | 23495.10 | 23495.11 | 23495.12 | 23495.13 | 23495.277 | 23495.278 | 23495.157 | 23495.158 | 23495.159 | 23495.145 | 23495.146 | 23495.147 | 23495.127 | 23495.128 | 23495.129 | 23495.112 | 23495.113 | 23495.114 | 23495.184 | 23495.185 | 23495.186 | 23495.148 | 23495.149 | 23495.150 | 23495.271 | 23495.272 | 23495.118 | 23495.119 | 23495.120 | 23495.106 | 23495.107 | 23495.108 | 23495.257 | 23495.258 | 23495.151 | 23495.152 | 23495.153 | 23495.31 | 23495.32 | 23495.33 | 23495.34 | 23495.136 | 23495.137 | 23495.138 | 23495.265 | 23495.266 | 23495.109 | 23495.110 | 23495.111 | 23495.261 | 23495.262 | 23495.115 | 23495.116 | 23495.117 | 23495.211 | 23495.212 | 23495.215 | 23495.216 | 2</atom>
        <atom name="AudRelatedGeography">México, Yucatán, North America</atom>
        <atom name="AudRelatedResourceID"></atom>
        <atom name="AudSex"></atom>
        <atom name="AudSubjectOrientation"></atom>
        <atom name="AudTaxonCoverage">xx99: Mexico: Yucatan: archaeology</atom>
        <atom name="AudTemporalCoverage"></atom>
        <atom name="AudVernacularName"></atom>
        <atom name="ChaAudioLength"></atom>
        <atom name="ChaFileSize">40270</atom>
        <atom name="ChaImageHeight">138</atom>
        <atom name="ChaImageWidth">238</atom>
        <atom name="ChaMd5Sum">00306823a5d509271027781db04f2946</atom>
        <atom name="ChaMediaForm">PDF document</atom>
        <atom name="ChaVideoFilmLength"></atom>
        <atom name="DetResourceType">Text</atom>
        <atom name="DetResourceSubtype"></atom>
        <tuple name="DetMediaRightsRef">
          <atom name="SummaryData">(c) Field Museum of Natural History - CC BY-NC 4.0</atom>
        </tuple>
        <atom name="MulMimeType">application</atom>
        <atom name="MulMimeFormat">pdf</atom>
        <atom name="MulIdentifier">RG0007_23495_Tag.pdf</atom>
        <table name="creator">
          <tuple>
            <atom name="NamFullName">Mr. Christopher J. Philipp</atom>
            <atom name="irn">407699</atom>
            <atom name="MulMultimediaCreatorRole">Scanner</atom>
          </tuple>
        </table>
        <atom name="RightsAcknowledgeLocal">Please cite this as: (c) The Field Museum (DATE) CC-BY-NC</atom>
        <atom name="MulTitle">23495 Tag</atom>
        <atom name="irn">1520526</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5 -->
  <tuple>
    <atom name="irn">3763547</atom>
    <atom name="DarGlobalUniqueIdentifier">1bb1501d-9f14-4ce1-a2df-988f535fe81d</atom>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <atom name="AdmDateInserted">2015-01-06</atom>
        <atom name="AdmDateModified">2021-10-04</atom>
        <atom name="AdmPublishWebNoPassword">Yes</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/805/047/129589CC.pdf</atom>
        <atom name="AudACDescription">scan of catalog card | FRONT]  | [MAIN BODY]  | Field Museum of Natural History. | [Field Museum Subject Code written in red] 34-46 | Country: Philippine Islands. | Locality: South Central Mindanao. | People: Bila-an. Stock. | Name: Balnatoñ: - Woman's anklets. Made similar to the wristlets of the same name. | | Collection: R.F. Cummings Philippine Expedition, 1909 -1911. F.C. Cole, Collector. | Notes: | Width: | Length: | Height: | Price: [Philippine peso symbol] 2.00 |  | [LEFT MARGIN] A | 129589 (1-2) | ENT | (1762) | Acc. 1139 [1115 crossed out] | L. | | [ILLUSTRATION] | | [ILLUSTRATION NOTATION] | | [BACK] |</atom>
        <atom name="AudAssociatedObservation"></atom>
        <atom name="AudAssociatedSpecimen">dcddad1e-8ce7-4857-8cc1-bb11ff24c684 | 1bb1501d-9f14-4ce1-a2df-988f535fe81d</atom>
        <atom name="AudCaptureDevice"></atom>
        <atom name="AudCitation">Courtesy of: D. Weddle, E. E. McKenna. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/4d7a8e1e-05d8-4e07-8b2c-88acfe9ba3db (accessed on 04 Oct 2021)</atom>
        <atom name="AudDerivedFrom"></atom>
        <atom name="AudFundingAttribution"></atom>
        <atom name="AudIdentifier">4d7a8e1e-05d8-4e07-8b2c-88acfe9ba3db</atom>
        <atom name="AudLifeStage"></atom>
        <atom name="AudNumbers">129589.2 | 129589.1 | 129589</atom>
        <atom name="AudRelatedGeography">Philippines, Mindanao Island, Asia</atom>
        <atom name="AudRelatedResourceID"></atom>
        <atom name="AudSex"></atom>
        <atom name="AudSubjectOrientation"></atom>
        <atom name="AudTaxonCoverage">3446: Philippines: ornaments, accessories</atom>
        <atom name="AudTemporalCoverage"></atom>
        <atom name="AudVernacularName"></atom>
        <atom name="ChaAudioLength"></atom>
        <atom name="ChaFileSize">193547</atom>
        <atom name="ChaImageHeight">283</atom>
        <atom name="ChaImageWidth">422</atom>
        <atom name="ChaMd5Sum">27c81cd031539086d234765018e3fc64</atom>
        <atom name="ChaMediaForm">PDF document</atom>
        <atom name="ChaVideoFilmLength"></atom>
        <atom name="DetResourceType">Text</atom>
        <atom name="DetResourceSubtype"></atom>
        <tuple name="DetMediaRightsRef">
          <atom name="SummaryData">(c) Field Museum of Natural History - CC BY-NC 4.0</atom>
        </tuple>
        <table name="DetSubject_tab">
          <tuple>
            <atom name="DetSubject">Philippines Heritage</atom>
          </tuple>
        </table>
        <atom name="MulMimeType">application</atom>
        <atom name="MulMimeFormat">pdf</atom>
        <atom name="MulIdentifier">129589CC.pdf</atom>
        <table name="creator">
          <tuple>
            <atom name="NamFullName">Dustin Weddle</atom>
            <atom name="irn">177275</atom>
            <atom name="MulMultimediaCreatorRole">Scanner</atom>
          </tuple>
          <tuple>
            <atom name="NamFullName">Etta E. McKenna</atom>
            <atom name="irn">186967</atom>
            <atom name="MulMultimediaCreatorRole">Transcriber</atom>
          </tuple>
        </table>
        <atom name="RightsAcknowledgeLocal">Please cite this as: (c) The Field Museum (DATE) CC-BY-NC</atom>
        <atom name="MulTitle">129589 Catalog Card</atom>
        <atom name="irn">805047</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6 -->
  <tuple>
    <atom name="irn">153530</atom>
    <atom name="DarGlobalUniqueIdentifier">e48acf38-2db7-4c09-b24b-32bd5bf91770</atom>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <atom name="AdmDateInserted">2020-08-06</atom>
        <atom name="AdmDateModified">2021-04-29</atom>
        <atom name="AdmPublishWebNoPassword">Yes</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/2196/097/CL0000_342710_7_InMountAngle.JPG</atom>
        <atom name="AudACDescription">reference image in mount, angle</atom>
        <atom name="AudAssociatedObservation"></atom>
        <atom name="AudAssociatedSpecimen">e48acf38-2db7-4c09-b24b-32bd5bf91770</atom>
        <atom name="AudCaptureDevice"></atom>
        <atom name="AudCitation">Courtesy of: C. J. Philipp. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/c05fc80c-1f2d-4122-8c4b-ce6876bf3d67 (accessed on 29 Apr 2021)</atom>
        <atom name="AudDerivedFrom"></atom>
        <atom name="AudFundingAttribution"></atom>
        <atom name="AudIdentifier">c05fc80c-1f2d-4122-8c4b-ce6876bf3d67</atom>
        <atom name="AudLifeStage"></atom>
        <atom name="AudNumbers">342710.7</atom>
        <atom name="AudRelatedGeography">México, North America</atom>
        <atom name="AudRelatedResourceID"></atom>
        <atom name="AudSex"></atom>
        <atom name="AudSubjectOrientation"></atom>
        <atom name="AudTaxonCoverage"></atom>
        <atom name="AudTemporalCoverage"></atom>
        <atom name="AudVernacularName"></atom>
        <atom name="ChaAudioLength"></atom>
        <atom name="ChaFileSize">3721164</atom>
        <atom name="ChaImageHeight">2649</atom>
        <atom name="ChaImageWidth">2500</atom>
        <atom name="ChaMd5Sum">989cc5d738862e6fa825d77faa9a55c8</atom>
        <atom name="ChaMediaForm"></atom>
        <atom name="ChaVideoFilmLength"></atom>
        <atom name="DetResourceType">StillImage</atom>
        <atom name="DetResourceSubtype"></atom>
        <tuple name="DetMediaRightsRef">
          <atom name="SummaryData">(c) Field Museum of Natural History - CC BY-NC 4.0</atom>
        </tuple>
        <atom name="MulMimeType">image</atom>
        <atom name="MulMimeFormat">jpeg</atom>
        <atom name="MulIdentifier">CL0000_342710_7_InMountAngle.JPG</atom>
        <table name="creator">
          <tuple>
            <atom name="NamFullName">Mr. Christopher J. Philipp</atom>
            <atom name="irn">407699</atom>
            <atom name="MulMultimediaCreatorRole">Photographer</atom>
          </tuple>
        </table>
        <atom name="RightsAcknowledgeLocal">Please cite this as: (c) The Field Museum (DATE) CC-BY-NC</atom>
        <atom name="MulTitle">342710.7 clay (ceramic) figurine</atom>
        <atom name="irn">2196097</atom>
      </tuple>
      <tuple>
        <atom name="AdmDateInserted">2020-08-06</atom>
        <atom name="AdmDateModified">2021-04-29</atom>
        <atom name="AdmPublishWebNoPassword">Yes</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/2196/096/CL0000_342710_7_InMount.JPG</atom>
        <atom name="AudACDescription">reference image in mount</atom>
        <atom name="AudAssociatedObservation"></atom>
        <atom name="AudAssociatedSpecimen">e48acf38-2db7-4c09-b24b-32bd5bf91770</atom>
        <atom name="AudCaptureDevice"></atom>
        <atom name="AudCitation">Courtesy of: C. J. Philipp. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/636266aa-f908-459a-ac7c-b9b89280968a (accessed on 29 Apr 2021)</atom>
        <atom name="AudDerivedFrom"></atom>
        <atom name="AudFundingAttribution"></atom>
        <atom name="AudIdentifier">636266aa-f908-459a-ac7c-b9b89280968a</atom>
        <atom name="AudLifeStage"></atom>
        <atom name="AudNumbers">342710.7</atom>
        <atom name="AudRelatedGeography">México, North America</atom>
        <atom name="AudRelatedResourceID"></atom>
        <atom name="AudSex"></atom>
        <atom name="AudSubjectOrientation"></atom>
        <atom name="AudTaxonCoverage"></atom>
        <atom name="AudTemporalCoverage"></atom>
        <atom name="AudVernacularName"></atom>
        <atom name="ChaAudioLength"></atom>
        <atom name="ChaFileSize">3387344</atom>
        <atom name="ChaImageHeight">2480</atom>
        <atom name="ChaImageWidth">2469</atom>
        <atom name="ChaMd5Sum">7bd6e3dcc4dfa6e7dca2b52c01835608</atom>
        <atom name="ChaMediaForm"></atom>
        <atom name="ChaVideoFilmLength"></atom>
        <atom name="DetResourceType">StillImage</atom>
        <atom name="DetResourceSubtype"></atom>
        <tuple name="DetMediaRightsRef">
          <atom name="SummaryData">(c) Field Museum of Natural History - CC BY-NC 4.0</atom>
        </tuple>
        <atom name="MulMimeType">image</atom>
        <atom name="MulMimeFormat">jpeg</atom>
        <atom name="MulIdentifier">CL0000_342710_7_InMount.JPG</atom>
        <table name="creator">
          <tuple>
            <atom name="NamFullName">Mr. Christopher J. Philipp</atom>
            <atom name="irn">407699</atom>
            <atom name="MulMultimediaCreatorRole">Photographer</atom>
          </tuple>
        </table>
        <atom name="RightsAcknowledgeLocal">Please cite this as: (c) The Field Museum (DATE) CC-BY-NC</atom>
        <atom name="MulTitle">342710.7 clay (ceramic) figurine</atom>
        <atom name="irn">2196096</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 7 -->
  <tuple>
    <atom name="irn">151896</atom>
    <atom name="DarGlobalUniqueIdentifier">40b583fd-b8b6-4831-9552-eddb17330a26</atom>
  </tuple>

  <!-- Row 8 -->
  <tuple>
    <atom name="irn">152504</atom>
    <atom name="DarGlobalUniqueIdentifier">41dd3a78-f540-475f-b075-32866cce7468</atom>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <atom name="AdmDateInserted">2020-08-06</atom>
        <atom name="AdmDateModified">2021-04-29</atom>
        <atom name="AdmPublishWebNoPassword">Yes</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/2195/815/CL0000_342710_5_InMount.JPG</atom>
        <atom name="AudACDescription">reference image in mount</atom>
        <atom name="AudAssociatedObservation"></atom>
        <atom name="AudAssociatedSpecimen">41dd3a78-f540-475f-b075-32866cce7468</atom>
        <atom name="AudCaptureDevice"></atom>
        <atom name="AudCitation">Courtesy of: C. J. Philipp. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/701edc73-6f7b-49b2-b0fc-bbbd6346430b (accessed on 29 Apr 2021)</atom>
        <atom name="AudDerivedFrom"></atom>
        <atom name="AudFundingAttribution"></atom>
        <atom name="AudIdentifier">701edc73-6f7b-49b2-b0fc-bbbd6346430b</atom>
        <atom name="AudLifeStage"></atom>
        <atom name="AudNumbers">342710.5</atom>
        <atom name="AudRelatedGeography">México, North America</atom>
        <atom name="AudRelatedResourceID"></atom>
        <atom name="AudSex"></atom>
        <atom name="AudSubjectOrientation"></atom>
        <atom name="AudTaxonCoverage"></atom>
        <atom name="AudTemporalCoverage"></atom>
        <atom name="AudVernacularName"></atom>
        <atom name="ChaAudioLength"></atom>
        <atom name="ChaFileSize">3629037</atom>
        <atom name="ChaImageHeight">1962</atom>
        <atom name="ChaImageWidth">3158</atom>
        <atom name="ChaMd5Sum">17f5b343ac8a3978ba4ded8b4d6088be</atom>
        <atom name="ChaMediaForm"></atom>
        <atom name="ChaVideoFilmLength"></atom>
        <atom name="DetResourceType">StillImage</atom>
        <atom name="DetResourceSubtype"></atom>
        <tuple name="DetMediaRightsRef">
          <atom name="SummaryData">(c) Field Museum of Natural History - CC BY-NC 4.0</atom>
        </tuple>
        <atom name="MulMimeType">image</atom>
        <atom name="MulMimeFormat">jpeg</atom>
        <atom name="MulIdentifier">CL0000_342710_5_InMount.JPG</atom>
        <table name="creator">
          <tuple>
            <atom name="NamFullName">Mr. Christopher J. Philipp</atom>
            <atom name="irn">407699</atom>
            <atom name="MulMultimediaCreatorRole">Photographer</atom>
          </tuple>
        </table>
        <atom name="RightsAcknowledgeLocal">Please cite this as: (c) The Field Museum (DATE) CC-BY-NC</atom>
        <atom name="MulTitle">342710.5 clay (ceramic) figurine</atom>
        <atom name="irn">2195815</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 9 -->
  <tuple>
    <atom name="irn">152315</atom>
    <atom name="DarGlobalUniqueIdentifier">44bc1ef9-5157-4d44-a737-4812ffc1e5a7</atom>
  </tuple>

  <!-- Row 10 -->
  <tuple>
    <atom name="irn">154226</atom>
    <atom name="DarGlobalUniqueIdentifier">2b8a8ec3-5274-404e-be05-ddd35011713d</atom>
  </tuple>
</table>
