<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    integer         cat_irn
    text short      DarGlobalUniqueIdentifier
    integer         CatAccessionYearLocal
    integer         DarCatalogNumberNumeric
    tuple           PriAccessionNumberRef
      text short      AccAccessionNo
      table           AccCollectorRef_tab
        text long       AccCollectorRef_tab_NamFullName
      end
    end
    text short      DarCatalogNumber
    table           OtherNums
      text short      CatOtherNumbersType
      text long       CatOtherNumbersValue
    end
    table           Description
      text long       DesKDescription
      text short      DesKType
      text short      DesKPreferred
    end
    table           DesUseClassification_tab
      text short      DesUseClassification
    end
    table           EcbPartsUsed_tab
      text short      EcbPartsUsed
    end
    table           DesEthnicGroupSubgroup_tab
      text short      DesEthnicGroupSubgroup
    end
    table           AttPeriod_tab
      text short      AttPeriod
    end
    table           DesMaterials_tab
      text short      DesMaterials
    end
    tuple           ColCollectionEventRef
      tuple           ColSiteRef
        integer         esites_irn
        text short      PolContinent
        text short      PolPD1
        text short      PolPD2
        text short      PolPD3
        text short      PolPopn
      end
    end
    text long       DarLocality
    integer         CatItemsCat
    integer         CatItemsInv
    table           DesObj
      text short      DesObjectName
      text short      DesObjectType
    end
    text short      DarCollector
    text short      CatRecordType
    text short      DesSubjectCode
    text short      DesPeriod
    text long       DesTechnicalDescription
    table           ColContinentLocal_tab
      text short      ColContinentLocal
    end
    table           ColCountryLocal_tab
      text short      ColCountryLocal
    end
    table           ColProvinceStateTerritoryLocal_tab
      text short      ColProvinceStateTerritoryLocal
    end
    table           ColDistrictCountyShireLocal_tab
      text short      ColDistrictCountyShireLocal
    end
    table           ColTownshipLocal_tab
      text short      ColTownshipLocal
    end
    integer         CatObjectCount
    integer         CatItemsSub
    text short      CatLegalStatus
    integer         CatAnthroCatalogNumber
    text long       CatSubNumbers
    table           Multimedia
      text short      AudIdentifier
      text short      AudAccessURI
      text short      AudCitation
      text short      emul_AdmPublishWebNoPassword
    end
    table           RefReferenceRef_tab
      integer         ebiblio_irn
      text long       ebiblio_SummaryData
    end
    table           RelObjectsRef_tab
      integer         ecatrel_irn
      text short      ecatrel_SummaryData
      text short      ecatrel_DarGlobalUniqueIdentifier
    end
    table           Measurement
      text short      MeaAnthroMeasurementTaken
      text short      MeaMammalsMeasurementTaken
      text short      MeaMeasurementKind
      text long       MeaMeasurementValue
      text short      MeaUnit
      text long       MeaFisRemarks
      date            MeaDateMeasured
      text long       eparties_NamBriefName
    end
    tuple           LocExhibitLocationRef
      integer         LocExhibitLocationRef_irn
    end
    tuple           LocTemporaryLocationRef
      integer         LocTemporaryLocationRef_irn
    end
  end
?>
<!-- Data -->
<table name="ecatalogue">

  <!-- Row 1 -->
  <tuple>
    <atom name="cat_irn">3808027</atom>
    <atom name="DarGlobalUniqueIdentifier">a3e1ffc0-3c29-4627-8be6-cb83f4257352</atom>
    <atom name="CatAccessionYearLocal">2019</atom>
    <atom name="DarCatalogNumberNumeric">360807</atom>
    <tuple name="PriAccessionNumberRef">
      <atom name="AccAccessionNo">4490</atom>
      <table name="AccCollectorRef_tab">
        <tuple>
          <atom name="AccCollectorRef_tab_NamFullName">Dr. Theresa L. Miller</atom>
        </tuple>
      </table>
    </tuple>
    <atom name="DarCatalogNumber">360807.nosub[1]</atom>
    <table name="OtherNums">
      <tuple>
        <atom name="CatOtherNumbersType">Tracking number</atom>
        <atom name="CatOtherNumbersValue">T2017.0012.000072</atom>
      </tuple>
    </table>
    <table name="Description">
      <tuple>
        <atom name="DesKDescription">basket</atom>
        <atom name="DesKType">Basic Description</atom>
        <atom name="DesKPreferred">Yes</atom>
      </tuple>
      <tuple>
        <atom name="DesKDescription">Object Name: Small basket / cestinha / kaj-re
Artist: Lindava Craxú Canela
Description: Small basket made of buriti / crowa pàr palm fibers (Mauritia flexuosa L.)
Location: Ramkokamekra-Canela Indigenous village of Escalvado in Terra Indígena (TI) Kanela, Maranhão State, Northeast Brazilian Cerrado (savannah)

This is a type of small basket (kaj-re in Canela) made of out native palm fibers (buriti in Portuguese; crowa pàr in Canela; Mauritia flexuosa L.). Buriti palm is one of the most ubiquitous palms in the local Cerrado (savannah) landscape and the palm fronds are used to make baskets, mats, houses, and many other objects that are part of Canela everyday life. The basket is painted with black paint from the fruits of the pau de leite (aramhôc pàr; Sapium gladulatum (Vell.) Pax) tree, indicating that it is meant for sale rather than everyday use. While the unpainted kaj-re small baskets are used in everyday life to carry garden produce and other items, the painted type is generally sold in nearby towns to tourists and/or non-Indigenous Brazilians. The geometric designs of the black paint are typical of this kind of basket.</atom>
        <atom name="DesKType">Source Description</atom>
        <atom name="DesKPreferred">No</atom>
      </tuple>
    </table>
    <table name="DesEthnicGroupSubgroup_tab">
      <tuple>
        <atom name="DesEthnicGroupSubgroup">Canela</atom>
      </tuple>
    </table>
    <table name="DesMaterials_tab">
      <tuple>
        <atom name="DesMaterials">fiber; palm leaf - buruti</atom>
      </tuple>
      <tuple>
        <atom name="DesMaterials">paint</atom>
      </tuple>
    </table>
    <tuple name="ColCollectionEventRef">
      <tuple name="ColSiteRef">
        <atom name="esites_irn">584757</atom>
        <atom name="PolContinent">South America</atom>
        <atom name="PolPD1">Brazil</atom>
        <atom name="PolPD2">Maranhão</atom>
        <atom name="PolPD3"></atom>
        <atom name="PolPopn">Escalvado</atom>
      </tuple>
    </tuple>
    <atom name="DarLocality">Escalvado</atom>
    <atom name="CatItemsCat">1</atom>
    <atom name="CatItemsInv">1</atom>
    <table name="DesObj">
      <tuple>
        <atom name="DesObjectName">kaj-re</atom>
        <atom name="DesObjectType">cultural</atom>
      </tuple>
      <tuple>
        <atom name="DesObjectName">cestinha</atom>
        <atom name="DesObjectType">cultural</atom>
      </tuple>
    </table>
    <atom name="DarCollector"></atom>
    <atom name="CatRecordType">Single</atom>
    <atom name="DesSubjectCode"></atom>
    <atom name="DesPeriod"></atom>
    <atom name="DesTechnicalDescription"></atom>
    <table name="ColContinentLocal_tab">
      <tuple>
        <atom name="ColContinentLocal">South America</atom>
      </tuple>
    </table>
    <table name="ColCountryLocal_tab">
      <tuple>
        <atom name="ColCountryLocal">Brazil</atom>
      </tuple>
    </table>
    <table name="ColProvinceStateTerritoryLocal_tab">
      <tuple>
        <atom name="ColProvinceStateTerritoryLocal">Maranhão</atom>
      </tuple>
    </table>
    <table name="ColTownshipLocal_tab">
      <tuple>
        <atom name="ColTownshipLocal">Escalvado</atom>
      </tuple>
    </table>
    <atom name="CatObjectCount">1</atom>
    <atom name="CatItemsSub">0</atom>
    <atom name="CatLegalStatus">Permanent Collection</atom>
    <atom name="CatAnthroCatalogNumber">360807</atom>
    <atom name="CatSubNumbers">nosub[1]</atom>
    <tuple name="LocExhibitLocationRef">
        <atom name="irn"></atom>
    </tuple>
    <tuple name="LocTemporaryLocationRef">
      <atom name="LocTemporaryLocationRef_irn">153938</atom>
    </tuple>
  </tuple>

  <!-- Row 2 -->
  <tuple>
    <atom name="cat_irn">3808034</atom>
    <atom name="DarGlobalUniqueIdentifier">d36d9d0c-f684-4308-8e18-34f5ac5cb01d</atom>
    <atom name="CatAccessionYearLocal">2019</atom>
    <atom name="DarCatalogNumberNumeric">360812</atom>
    <tuple name="PriAccessionNumberRef">
      <atom name="AccAccessionNo">4490</atom>
      <table name="AccCollectorRef_tab">
        <tuple>
          <atom name="AccCollectorRef_tab_NamFullName">Dr. Theresa L. Miller</atom>
        </tuple>
      </table>
    </tuple>
    <atom name="DarCatalogNumber">360812.nosub[1]</atom>
    <table name="OtherNums">
      <tuple>
        <atom name="CatOtherNumbersType">Tracking number</atom>
        <atom name="CatOtherNumbersValue">T2017.0012.000079</atom>
      </tuple>
    </table>
    <table name="Description">
      <tuple>
        <atom name="DesKDescription">necklace</atom>
        <atom name="DesKType">Basic Description</atom>
        <atom name="DesKPreferred">Yes</atom>
      </tuple>
      <tuple>
        <atom name="DesKDescription">Object Name: Beaded necklace made w/ seeds from native plant (tiririca / capà-ti hỳ)
Artist: Jose Diogo Pep-re Canela
Description: Jewelry / miçanga / kẽn-re made of native plant seeds (tiririca / capà-ti hỳ); wooden pendant made of sucupira / cuhtà caxwỳn pàr)
Location: Ramkokamekra-Canela Indigenous village of Escalvado in Terra Indígena (TI) Kanela, Maranhão State, Northeast Brazilian Cerrado (savannah)

This type of seed bead necklace is traditional to the Canela but is no longer commonly made because purchased glass and plastic beads have largely replaced the practice of making beads out of native seeds in the local environment. The wooden pendant is made out of sucupira wood (Diplotropis purpurea [Rich.] Amshoff) which is commonly deforested (both legally and illegally) in the Cerrado and exported within and outside Brazil for timber, furniture, and wooden flooring. The pendant is painted with red annatto (urucum, pym in Canela) paste, the fruits of which are boiled down to make the bright red paste that is used to decorate ritual objects and as ritual body paint. This necklace was definitely used and worn prior to its purchase, likely by the artist himself. Although it is not unheard of for men to make the beaded jewelry (miçanga in Portuguese or kẽn-re in Canela), women typically make the jewelry for ritual and everyday use.
The artist, Jose Diogo Pep-re Canela, is an interesting person in the community. He is one of the community’s elderly shamans, or kay in Canela, and therefore has developed heightened sensory abilities to communicate with deceased souls or spirits, known as mekarõn in Canela. Illnesses are thought to be caused by the deceased mekarõn convincing the living person’s soul to leave his/her body, and shamans cure illnesses through communicating with the mekarõn to let the living person’s soul return to the body. They do this by laying hands and blowing tobacco smoke on the ill person’s body. Being and becoming a shaman is difficult and requires months and years of food and sex prohibitions known as resguardo, and being taught by a mekarõn soul teacher, in order to achieve the heightened sensory abilities. Shamans can also communicate with animals, plants, objects and artifacts, and essentially all nonhuman beings. Shamans speak with the master spirits of plants, known as Plant-Men and Plant-Women, and serve as mediators between human gardeners and their growing plants, which are considered children in need of affectionate care and attention.</atom>
        <atom name="DesKType">Source Description</atom>
        <atom name="DesKPreferred">No</atom>
      </tuple>
    </table>
    <table name="DesEthnicGroupSubgroup_tab">
      <tuple>
        <atom name="DesEthnicGroupSubgroup">Canela</atom>
      </tuple>
    </table>
    <table name="DesMaterials_tab">
      <tuple>
        <atom name="DesMaterials">seed</atom>
      </tuple>
      <tuple>
        <atom name="DesMaterials">wood; sucupira</atom>
      </tuple>
      <tuple>
        <atom name="DesMaterials">paint (annatto)</atom>
      </tuple>
    </table>
    <tuple name="ColCollectionEventRef">
      <tuple name="ColSiteRef">
        <atom name="esites_irn">584757</atom>
        <atom name="PolContinent">South America</atom>
        <atom name="PolPD1">Brazil</atom>
        <atom name="PolPD2">Maranhão</atom>
        <atom name="PolPD3"></atom>
        <atom name="PolPopn">Escalvado</atom>
      </tuple>
    </tuple>
    <atom name="DarLocality">Escalvado</atom>
    <atom name="CatItemsCat">1</atom>
    <atom name="CatItemsInv">1</atom>
    <table name="DesObj">
      <tuple>
        <atom name="DesObjectName">kẽn-re</atom>
        <atom name="DesObjectType">cultural</atom>
      </tuple>
      <tuple>
        <atom name="DesObjectName">miçanga</atom>
        <atom name="DesObjectType">cultural</atom>
      </tuple>
    </table>
    <atom name="DarCollector"></atom>
    <atom name="CatRecordType">Single</atom>
    <atom name="DesSubjectCode"></atom>
    <atom name="DesPeriod"></atom>
    <atom name="DesTechnicalDescription"></atom>
    <table name="ColContinentLocal_tab">
      <tuple>
        <atom name="ColContinentLocal">South America</atom>
      </tuple>
    </table>
    <table name="ColCountryLocal_tab">
      <tuple>
        <atom name="ColCountryLocal">Brazil</atom>
      </tuple>
    </table>
    <table name="ColProvinceStateTerritoryLocal_tab">
      <tuple>
        <atom name="ColProvinceStateTerritoryLocal">Maranhão</atom>
      </tuple>
    </table>
    <table name="ColTownshipLocal_tab">
      <tuple>
        <atom name="ColTownshipLocal">Escalvado</atom>
      </tuple>
    </table>
    <atom name="CatObjectCount">1</atom>
    <atom name="CatItemsSub">0</atom>
    <atom name="CatLegalStatus">Permanent Collection</atom>
    <atom name="CatAnthroCatalogNumber">360812</atom>
    <atom name="CatSubNumbers">nosub[1]</atom>
    <tuple name="LocExhibitLocationRef">
        <atom name="irn"></atom>
    </tuple>
    <tuple name="LocTemporaryLocationRef">
      <atom name="LocTemporaryLocationRef_irn">153938</atom>
    </tuple>
  </tuple>

  <!-- Row 3 -->
  <tuple>
    <atom name="cat_irn">3808032</atom>
    <atom name="DarGlobalUniqueIdentifier">f80828f0-6c10-4486-851d-ed8d9a1c260f</atom>
    <atom name="CatAccessionYearLocal">2019</atom>
    <atom name="DarCatalogNumberNumeric">360811</atom>
    <tuple name="PriAccessionNumberRef">
      <atom name="AccAccessionNo">4490</atom>
      <table name="AccCollectorRef_tab">
        <tuple>
          <atom name="AccCollectorRef_tab_NamFullName">Dr. Theresa L. Miller</atom>
        </tuple>
      </table>
    </tuple>
    <atom name="DarCatalogNumber">360811.nosub[1]</atom>
    <table name="OtherNums">
      <tuple>
        <atom name="CatOtherNumbersType">Tracking number</atom>
        <atom name="CatOtherNumbersValue">T2017.0012.000077</atom>
      </tuple>
    </table>
    <table name="Description">
      <tuple>
        <atom name="DesKDescription">rattle</atom>
        <atom name="DesKType">Basic Description</atom>
        <atom name="DesKPreferred">Yes</atom>
      </tuple>
      <tuple>
        <atom name="DesKDescription">Object Name: Small bottle gourd rattle / cabaça / cuhtõj kryi-re
Artist: Severio Hoku Canela
Description: Made of a small bottle gourd (Lagenaria siceraria (Molina) Standl. and/or Crescentia cujete L.), with cotton string (algodão / caxàt) and native seeds (catêc-re hy)
Location: Ramkokamekra-Canela Indigenous village of Escalvado in Terra Indígena (TI) Kanela, Maranhão State, Northeast Brazilian Cerrado (savannah)
This is a typical Canela gourd rattle, used in ritual singing activities by the male lead ritual singer in the ceremonial center of the concentric circular village space (see Crocker 1990 and Miller 2019). The rattle is made out of a small bottle gourd known as cuhtõj kryi-re (Lagenaria siceraria (Molina) Standl. and/or Crescentia cujete L.), which is one of three types of bottle gourd and one of the 12 types of gourd that is still cultivated by Canela gardeners. The green cotton strings on the top and bottom of the gourd are decorative and likely store-bought. Canela gardeners traditionally grew cotton (caxàt) varietals in the past and a few still do today, but it is much less common than half a century ago. Nowadays most people buy cotton strings in nearby towns, such as this colored type. The white cotton string attached to the rattle’s handle could possibly be native Canela cotton or store-bought. The rattle’s handle is made out of a lighter type of wood (not sucupira, which has a dark brown-purplish color). The gourd is filled with native catêc-re plant seeds (hy) to make the rattling percussion noise. These seeds have red and white markings and are commonly found throughout the Canela territory. There is also a type of cultivated bean, pànkrỳt catêc-re hy (Phaseolus vulgaris L.) that is named after the seeds, demonstrating their importance in the Canela socio-ecological system.
The artist, Severio Hoku Canela, was one of the collector’s main research assistants during her fieldwork in 2012-2013. He is a well-known gardener and political leader in the village, and he made this rattle for use in male ritual singing activities. Although he is not a lead singer, the rattle was likely made for someone in his close family who has developed that particular skill.</atom>
        <atom name="DesKType">Source Description</atom>
        <atom name="DesKPreferred">No</atom>
      </tuple>
      <tuple>
        <atom name="DesKDescription">Idiophone</atom>
        <atom name="DesKType">Technical Description</atom>
        <atom name="DesKPreferred">No</atom>
      </tuple>
    </table>
    <table name="DesEthnicGroupSubgroup_tab">
      <tuple>
        <atom name="DesEthnicGroupSubgroup">Canela</atom>
      </tuple>
    </table>
    <table name="DesMaterials_tab">
      <tuple>
        <atom name="DesMaterials">gourd</atom>
      </tuple>
      <tuple>
        <atom name="DesMaterials">cotton</atom>
      </tuple>
      <tuple>
        <atom name="DesMaterials">seed</atom>
      </tuple>
    </table>
    <tuple name="ColCollectionEventRef">
      <tuple name="ColSiteRef">
        <atom name="esites_irn">584757</atom>
        <atom name="PolContinent">South America</atom>
        <atom name="PolPD1">Brazil</atom>
        <atom name="PolPD2">Maranhão</atom>
        <atom name="PolPD3"></atom>
        <atom name="PolPopn">Escalvado</atom>
      </tuple>
    </tuple>
    <atom name="DarLocality">Escalvado</atom>
    <atom name="CatItemsCat">1</atom>
    <atom name="CatItemsInv">1</atom>
    <table name="DesObj">
      <tuple>
        <atom name="DesObjectName">cuhtõj kryi-re</atom>
        <atom name="DesObjectType">cultural</atom>
      </tuple>
      <tuple>
        <atom name="DesObjectName">maracá de cabaça</atom>
        <atom name="DesObjectType">cultural</atom>
      </tuple>
    </table>
    <atom name="DarCollector"></atom>
    <atom name="CatRecordType">Single</atom>
    <atom name="DesSubjectCode"></atom>
    <atom name="DesPeriod"></atom>
    <atom name="DesTechnicalDescription"></atom>
    <table name="ColContinentLocal_tab">
      <tuple>
        <atom name="ColContinentLocal">South America</atom>
      </tuple>
    </table>
    <table name="ColCountryLocal_tab">
      <tuple>
        <atom name="ColCountryLocal">Brazil</atom>
      </tuple>
    </table>
    <table name="ColProvinceStateTerritoryLocal_tab">
      <tuple>
        <atom name="ColProvinceStateTerritoryLocal">Maranhão</atom>
      </tuple>
    </table>
    <table name="ColTownshipLocal_tab">
      <tuple>
        <atom name="ColTownshipLocal">Escalvado</atom>
      </tuple>
    </table>
    <atom name="CatObjectCount">1</atom>
    <atom name="CatItemsSub">0</atom>
    <atom name="CatLegalStatus">Permanent Collection</atom>
    <atom name="CatAnthroCatalogNumber">360811</atom>
    <atom name="CatSubNumbers">nosub[1]</atom>
    <table name="RefReferenceRef_tab">
      <tuple>
        <atom name="ebiblio_irn">37723</atom>
        <atom name="ebiblio_SummaryData">[Book] Miller, Theresa L. Plant Kin: A Multispecies Ethnography in Indigenous Brazil. 328.</atom>
      </tuple>
    </table>
    <tuple name="LocExhibitLocationRef">
        <atom name="irn"></atom>
    </tuple>
    <tuple name="LocTemporaryLocationRef">
      <atom name="LocTemporaryLocationRef_irn">153938</atom>
    </tuple>
  </tuple>

  <!-- Row 4 -->
  <tuple>
    <atom name="cat_irn">3630556</atom>
    <atom name="DarGlobalUniqueIdentifier">29cf43da-7863-4f6a-af06-b88df84cfd24</atom>
    <atom name="CatAccessionYearLocal">1896</atom>
    <atom name="DarCatalogNumberNumeric">23495</atom>
    <tuple name="PriAccessionNumberRef">
      <atom name="AccAccessionNo">253</atom>
      <table name="AccCollectorRef_tab">
        <tuple>
          <atom name="AccCollectorRef_tab_NamFullName">Edward H. Thompson</atom>
        </tuple>
      </table>
    </tuple>
    <atom name="DarCatalogNumber">23495.102</atom>
    <table name="OtherNums">
      <tuple>
        <atom name="CatOtherNumbersValue">95</atom>
      </tuple>
    </table>
    <table name="Description">
      <tuple>
        <atom name="DesKDescription">fragment</atom>
        <atom name="DesKType">Basic Description</atom>
        <atom name="DesKPreferred">Yes</atom>
      </tuple>
      <tuple>
        <atom name="DesKDescription">1 of 280 bits of stone and bag of stone fragments from box of bits (fragments) of stone; tag with object reads, "potter's earth - - used by the natives of Yucatan in making both the ancient and modern vessels"</atom>
        <atom name="DesKType">Full Description</atom>
        <atom name="DesKPreferred">No</atom>
      </tuple>
      <tuple>
        <atom name="DesKPreferred">No</atom>
      </tuple>
    </table>
    <table name="DesEthnicGroupSubgroup_tab">
      <tuple>
        <atom name="DesEthnicGroupSubgroup">Maya</atom>
      </tuple>
    </table>
    <table name="DesMaterials_tab">
      <tuple>
        <atom name="DesMaterials">stone</atom>
      </tuple>
    </table>
    <tuple name="ColCollectionEventRef">
      <tuple name="ColSiteRef">
        <atom name="esites_irn">406172</atom>
        <atom name="PolContinent">North America</atom>
        <atom name="PolPD1">México</atom>
        <atom name="PolPD2">Yucatán</atom>
        <atom name="PolPD3"></atom>
        <atom name="PolPopn">Xkichmook</atom>
      </tuple>
    </tuple>
    <atom name="DarLocality">Xkichmook</atom>
    <atom name="CatItemsCat">1</atom>
    <atom name="CatItemsInv">1</atom>
    <table name="DesObj">
      <tuple>
        <atom name="DesObjectName">kat</atom>
        <atom name="DesObjectType">cultural</atom>
      </tuple>
    </table>
    <atom name="DarCollector">Collector</atom>
    <atom name="CatRecordType">Child</atom>
    <atom name="DesSubjectCode">xx99: Mexico: Yucatan: archaeology</atom>
    <atom name="DesPeriod"></atom>
    <atom name="DesTechnicalDescription"></atom>
    <table name="ColContinentLocal_tab">
      <tuple>
        <atom name="ColContinentLocal">North America</atom>
      </tuple>
    </table>
    <table name="ColCountryLocal_tab">
      <tuple>
        <atom name="ColCountryLocal">México</atom>
      </tuple>
    </table>
    <table name="ColProvinceStateTerritoryLocal_tab">
      <tuple>
        <atom name="ColProvinceStateTerritoryLocal">Yucatán</atom>
      </tuple>
    </table>
    <table name="ColTownshipLocal_tab">
      <tuple>
        <atom name="ColTownshipLocal">Xkichmook</atom>
      </tuple>
    </table>
    <atom name="CatObjectCount">1</atom>
    <atom name="CatItemsSub">1</atom>
    <atom name="CatLegalStatus">Permanent Collection</atom>
    <atom name="CatAnthroCatalogNumber">23495</atom>
    <atom name="CatSubNumbers">.102</atom>
    <table name="Multimedia">
      <tuple>
        <atom name="AudIdentifier">aed844e7-f998-4d0d-87d7-d35a4cde098f</atom>
        <atom name="AudAccessURI"></atom>
        <atom name="AudCitation">Courtesy of: C. Pontone. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/aed844e7-f998-4d0d-87d7-d35a4cde098f (accessed on 11 Mar 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">No</atom>
      </tuple>
      <tuple>
        <atom name="AudIdentifier">fc7f8eb5-0253-497d-9e5e-f299bc54d0bf</atom>
        <atom name="AudAccessURI"></atom>
        <atom name="AudCitation">Courtesy of: C. J. Philipp. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/fc7f8eb5-0253-497d-9e5e-f299bc54d0bf (accessed on 11 Mar 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">No</atom>
      </tuple>
    </table>
    <tuple name="LocExhibitLocationRef">
        <atom name="irn"></atom>
    </tuple>
    <tuple name="LocTemporaryLocationRef">
        <atom name="irn"></atom>
    </tuple>
  </tuple>

  <!-- Row 5 -->
  <tuple>
    <atom name="cat_irn">3763547</atom>
    <atom name="DarGlobalUniqueIdentifier">1bb1501d-9f14-4ce1-a2df-988f535fe81d</atom>
    <atom name="CatAccessionYearLocal">1911</atom>
    <atom name="DarCatalogNumberNumeric">129589</atom>
    <tuple name="PriAccessionNumberRef">
      <atom name="AccAccessionNo">1139</atom>
      <table name="AccCollectorRef_tab">
        <tuple>
          <atom name="AccCollectorRef_tab_NamFullName">Dr. Fay-Cooper Cole</atom>
        </tuple>
      </table>
    </tuple>
    <atom name="DarCatalogNumber">129589.1</atom>
    <table name="OtherNums">
      <tuple>
        <atom name="CatOtherNumbersType">Fieldwork number</atom>
        <atom name="CatOtherNumbersValue">1762</atom>
      </tuple>
    </table>
    <table name="Description">
      <tuple>
        <atom name="DesKDescription">anklet</atom>
        <atom name="DesKType">Basic Description</atom>
        <atom name="DesKPreferred">Yes</atom>
      </tuple>
      <tuple>
        <atom name="DesKDescription">Name: Balnatoñ: - Woman's anklets. Made similar to the wristlets of the same name.</atom>
        <atom name="DesKType">Full Description</atom>
        <atom name="DesKPreferred">Yes</atom>
      </tuple>
    </table>
    <table name="DesEthnicGroupSubgroup_tab">
      <tuple>
        <atom name="DesEthnicGroupSubgroup">Blaan</atom>
      </tuple>
    </table>
    <table name="DesMaterials_tab">
      <tuple>
        <atom name="DesMaterials">metal; brass</atom>
      </tuple>
    </table>
    <tuple name="ColCollectionEventRef">
      <tuple name="ColSiteRef">
        <atom name="esites_irn">401931</atom>
        <atom name="PolContinent">Asia</atom>
        <atom name="PolPD1">Philippines</atom>
        <atom name="PolPD2">Mindanao Island</atom>
        <atom name="PolPD3"></atom>
        <atom name="PolPopn"></atom>
      </tuple>
    </tuple>
    <atom name="DarLocality"></atom>
    <atom name="CatItemsCat">1</atom>
    <atom name="CatItemsInv">1</atom>
    <table name="DesObj">
      <tuple>
        <atom name="DesObjectName">balnatōñ</atom>
        <atom name="DesObjectType">cultural</atom>
      </tuple>
    </table>
    <atom name="DarCollector">Collector</atom>
    <atom name="CatRecordType">Child</atom>
    <atom name="DesSubjectCode">3446: Philippines: ornaments, accessories</atom>
    <atom name="DesPeriod"></atom>
    <atom name="DesTechnicalDescription"></atom>
    <table name="ColContinentLocal_tab">
      <tuple>
        <atom name="ColContinentLocal">Asia</atom>
      </tuple>
    </table>
    <table name="ColCountryLocal_tab">
      <tuple>
        <atom name="ColCountryLocal">Philippines</atom>
      </tuple>
    </table>
    <table name="ColProvinceStateTerritoryLocal_tab">
      <tuple>
        <atom name="ColProvinceStateTerritoryLocal">Mindanao Island</atom>
      </tuple>
    </table>
    <atom name="CatObjectCount">1</atom>
    <atom name="CatItemsSub">1</atom>
    <atom name="CatLegalStatus">Permanent Collection</atom>
    <atom name="CatAnthroCatalogNumber">129589</atom>
    <atom name="CatSubNumbers">.1</atom>
    <table name="Multimedia">
      <tuple>
        <atom name="AudIdentifier">4d7a8e1e-05d8-4e07-8b2c-88acfe9ba3db</atom>
        <atom name="AudAccessURI">http://fm-digital-assets.fieldmuseum.org/805/047/129589CC.pdf</atom>
        <atom name="AudCitation">Courtesy of: D. Weddle, E. E. McKenna. (c) Field Museum of Natural History. CC BY-NC 4.0. https://mm.fieldmuseum.org/4d7a8e1e-05d8-4e07-8b2c-88acfe9ba3db (accessed on 04 Oct 2021)</atom>
        <atom name="emul_AdmPublishWebNoPassword">Yes</atom>
      </tuple>
    </table>
    <tuple name="LocExhibitLocationRef">
        <atom name="irn"></atom>
    </tuple>
    <tuple name="LocTemporaryLocationRef">
        <atom name="irn"></atom>
    </tuple>
  </tuple>

  <!-- Row 6 -->
  <tuple>
    <atom name="cat_irn">153530</atom>
    <atom name="DarGlobalUniqueIdentifier">e48acf38-2db7-4c09-b24b-32bd5bf91770</atom>
    <atom name="CatAccessionYearLocal">2008</atom>
    <atom name="DarCatalogNumberNumeric">342710</atom>
    <tuple name="PriAccessionNumberRef">
      <atom name="AccAccessionNo">4297</atom>
      <table name="AccCollectorRef_tab">
        <tuple>
          <atom name="AccCollectorRef_tab_NamFullName">William S. Goldman</atom>
        </tuple>
      </table>
    </tuple>